### ISSUE TITLE
Direct ByteBuffer compression seems not be possible?

### ISSUE THREAD

**Issue by foosmate** [hyperxpro/Brotli4j#35]
First of all thank you so much for this great brotli library providing *both* decompressor *and* compressor.

There are many use cases where you simply want to compress small byte-buffers without any need for channel or stream operation. This doesn't seem to be possible on Brotli4j's current API, although the neccessary methods (under the hood) for direct byte-buffer operation are all there.

In our actual use case we need to compress self-contained chunks (few KB) from a byte-buffer ```src``` into a byte-buffer ```dst```. Currently we pass the whole content blockwise through a ```WritableByteChannel``` and then collect the compressed data chunks back to a 2nd destination byte-buffer. This works, but is very "cumbersome".

Since we have thousands of small chunks to be compressed we currently suffer from the fact that you can not *reuse* the channel. For each new small chunk we have to create a new channel, which creates a complete encoder and destroys it on closing. As quick fix it would be very helpful to be able to reset a channel in order to reuse it. This would significantly improve the performance for such use cases.

Some other libraries (LZ4, ZStd, etc.) provide easy access methods for direct byte-buffers like this:

    static int maxCompressSize(int uncompressSize);
    static int compress(ByteBuffer src, ByteBuffer dst);
    static void uncompress(ByteBuffer src, ByteBuffer dst, int uncompressSize);

This would be a great extension for this library making the life much easier in these use cases.

The existing encoder methods to process ```byte[]``` arrays is not an option for us because these produces a lot of garbage (tons of small byte arrays) in our messaging system. Thus re-using direct byte-buffers would me much more relaxing for the GC.

**Comment by hyperxpro** [comment]
Thanks for letting me know about the areas where Brotli4j can be improved.

Have you implemented direct ByteBuffer yourself? If yes, can you do PR?

**Comment by Foosmate** [comment]
I already have looked for doing a PR, but this requires some knowledge about the internal encoder. The current method for handling byte arrays creates and destroys a encoder with every call. I think it would be much better to keep the encoder (e.g. in a ThreadLocal) and reuse it as much as possible. Otherwise there will be a lot of resources spent in GC and thousands of init/destroy cycles.

**Comment by Foosmate** [comment]
Looks like you found several points that resulted in a significant throughput improvement. That's great ...
:-)

**Comment by Foosmate** [comment]
Thanks for adding byte buffer support. :-)

I just have a short look to commit 78e7e403b4 and here are some hints:

1. If `src` buffer is empty there is nothing written to `dst` buffer. The `byte[]` version adds a single empty byte indicator for this case (line 87 vs line 118).
2. If the encoder wants to add more output to the destination byte buffer, `dst.flip()` must not be called multiple times (looks so in line 100).
3. If underlying Brotli implementation enforces direct byte buffers (I don't know) this may need to be checked as precondition.

**Comment by slandelle** [comment]
> If underlying Brotli implementation enforces direct byte buffers (I don't know) this may need to be checked as precondition.

Because JNI only supports byte arrays and direct ByteBuffers.

**Comment by Foosmate** [comment]
Ah, I just realize that the src buffer is always copied into a direct buffer that was provided by the encoder.

@hyperxpro Is these double buffer copy in / out necessary for byte buffers? Or does the brotli library also allow to pass a direct buffer which would be more efficient (makes sense, if direct buffers were already passed to the method)?

**Comment by Foosmate** [comment]
On the other hand we should have an eye on creating direct byte buffers under pressure with high frequency. For me it looks as the direct buffer that is returned by `EncoderJNI.nativeCreate(context)` has to be released by the GC.

Direct byte buffers do not automatically respond to pressure on the native heap. Since direct byte buffers are internally released later (async) you can easily out-of-mem yourself by simply creating direct byte buffers too fast (even as method field).

Thus it may be more reliable to *pass* a given direct byte buffer to the encoder instead of retrieving a short living one each time.

**Comment by Foosmate** [comment]
I thought about this a little bit more ...

It would certainly be the best if the JNI encoder could accept direct byte buffers instead of creating its own each time (which may produces tons of async garbage under heavy load).

But assuming this change is too large, we could at least optimize `compress(byte[])` and `compress(ByteBuffer)` so that internally the entire source size is *not* requested as one large byte buffer by the encoder. Instead, I really like the incremental solution that already is implemented in `BrotliEncoderChannel`. Here a small 16 KB direct byte buffer is created and then re-used again and again to compress much larger amounts of data in the end. The same incremental approach could be used for both static compress methods for byte arrays and buffers as well. 

This little optimization would ensure that no large (could be hundreds of MB) short-living direct byte buffers are created per call?

**Comment by hyperxpro** [comment]
I will add `ByteBuffer` pooling in another PR because I need extra time to work on it.

**Comment by foosmate** [comment]
Instead of complex buffer pooling you even could create a single 16KB direct buffer and make this thread-local. This would allow you to incrementally feed the brotli encoder (like you already do in `BrotliEncoderChannel`) by always re-using this single cached buffer and there is no intermediate garbage anymore. I guess this way would be a quick win with less effort than pooling and it would be completely solve the problem.

**Comment by hyperxpro** [comment]
Would you like to do PR for this?

**Comment by foosmate** [comment]
We have a project that is terminated by the end of next month, after that I will can do a PR for this.

For the moment flipping the buffer at the end is still somehow unexpected ...

    if (dstPosition != dst.position()) {
        dst.flip();
    }

Would you mind, to remove this flipping?

Check here, how other libraries handle this:

https://github.com/lz4/lz4-java/blob/a9c1b3a7d51115694ecee0976884f91cf9053d5a/src/java/net/jpountz/lz4/LZ4Compressor.java#L159

https://github.com/luben/zstd-jni/blob/31060934c26e080031465702ec369591e12874f8/src/main/java/com/github/luben/zstd/ZstdCompressCtx.java#L282

**Comment by hyperxpro** [comment]
Since it's internal, I'd keep `flip` to keep things simple. Because even I follow Zstd or lz4 way, it's the same thing.

**Comment by foosmate** [comment]
You flip the *external* `dst` byte buffer that was passed as argument to the method.

https://github.com/hyperxpro/Brotli4j/blob/6a2903e47381445370274c0dc6ea891fc6990621/brotli4j/src/main/java/com/aayushatharva/brotli4j/encoder/Encoder.java#L118

This behavior is different than from LZ4 and ZSTD (check last line of this output):

    srcLz4: java.nio.HeapByteBuffer[pos=300 lim=300 cap=1024]
    dstLz4: java.nio.HeapByteBuffer[pos=442 lim=800 cap=1024]
    
    srcZstd: java.nio.HeapByteBuffer[pos=300 lim=300 cap=1024]
    dstZstd: java.nio.HeapByteBuffer[pos=442 lim=800 cap=1024]
    
    srcBrotli: java.nio.HeapByteBuffer[pos=300 lim=300 cap=1024]
    dstBrotli: java.nio.HeapByteBuffer[pos=0 lim=442 cap=1024]

Flipping should only be done intentionally by the API user (in the external context).
